<a href="https://colab.research.google.com/github/diazonic/ask-us-anything/blob/master/Diazonic_Labs_Ask_Us_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. What is the difference between iloc and reshape(-1,1)

In [0]:
import numpy as np
import pandas as pd
ip = np.arange(1,7,1)
ip

array([1, 2, 3, 4, 5, 6])

In [0]:
print(ip.ndim)
print(ip)

1
[1 2 3 4 5 6]


In [0]:
d = {'Input':ip}
df = pd.DataFrame(d)
df

Input
0      1
1      2
2      3
3      4
4      5
5      6

In [0]:
#iloc : Index Location

In [0]:
x = df.iloc[:,[0]].values
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [0]:
#In sklearn, we should input in 2D

In [0]:
print(x.ndim)
print(x.shape)

2
(6, 1)


In [0]:
print(ip)
print(ip.ndim)
print(ip.shape)

[1 2 3 4 5 6]
1
(6,)


In [0]:
x1 = ip.reshape(-1,1) 
print(x1)
print(x1.ndim)
print(x1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
2
(6, 1)


In [0]:
x1 = ip.reshape(-1,6)
print(x1)
print(x1.ndim)
print(x1.shape)

[[1 2 3 4 5 6]]
2
(1, 6)
